Create lect12.md
ucsb-cs9/s24-ykk pull request #20
Opened 2024-05-11 19:10 UTC by eshagupta01

2024-05-14 19:08 UTC, ykharitonova requested changes
@eshagupta01 Thanks for putting together the notes, Esha.

I added a few comments for you to please address before I pull the notes in.

2024-05-14 19:08 UTC, ykharitonova commented on _lectures/lect12.md
> +[Recorded video]()
no need to include this for lectures that don't have a recording

2024-05-14 19:08 UTC, ykharitonova commented on _lectures/lect12.md
> +Iclicker review of last class
needs bullet points

2024-05-14 19:08 UTC, ykharitonova commented on _lectures/lect12.md
> +A. next
perhaps add it to the code block, so that the options are formatted as Markdown correctly instead of running into one another.
alternatively, separate them by a blank line.

2024-05-14 19:08 UTC, ykharitonova commented on _lectures/lect12.md
> +- Add practice for overloading operators
Is this a TODO for me? If so, can you please add the tag, so that I can quickly update the files by searching for it?

2024-05-14 19:08 UTC, ykharitonova commented on _lectures/lect12.md
> +# Sorting
need a link to the viz: https://www.hackerearth.com/practice/algorithms/sorting/bubble-sort/visualize/

2024-05-16 21:14 UTC, ykharitonova commented
@eshagupta01 could you please make the changes and update the PR?

2024-05-16 22:23 UTC, eshagupta01 commented on _lectures/lect12.md
> +A. next
I added a code block using the "  ''''  " but let me know if you wanted something else

2024-05-17 20:33 UTC, ykharitonova commented on _lectures/lect12.md
> +A. next
Note that the code block is done using the backticks \`, not the quotations. :-)

2024-05-17 20:33 UTC, merged